version: '3.8'

services:
  vote-app:
    build: ./vote
    ports:
      - "5000:8080"
    container_name: vote-container
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  result-app:
    build: ./result
    ports:
      - "3000:8888"
    container_name: result-container
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votes_db

  worker-app:
    build: ./worker
    container_name: worker-container
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votes_db

  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votes_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
    db-data:


